---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    storageclass.kubernetes.io/is-default-class: "true"
  name: microk8s-hostpath
provisioner: microk8s.io/hostpath
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer