---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: microk8s-hostpath-ssd
provisioner: microk8s.io/hostpath
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  pvDir: /data/ssd
volumeBindingMode: WaitForFirstConsumer