---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  interval: 24h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  dependsOn:
    - name: minio-operator
      namespace: minio-operator
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: tenant
      version: "5.0.11"
      sourceRef:
        kind: HelmRepository
        name: minio-tenant
        namespace: minio-tenant
      interval: 12h
  values:
    secrets:
      name: myminio-env-configuration
      accessKey: minio 
      secretKey: minio123
    tenant:
      name: myminio
      configuration:
        name: myminio-env-configuration
      pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        size: 25Gi
