---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  dependsOn:
    - name: minio-operator
      namespace: minio-operator
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: tenant
      version: "6.0.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 12h
  values:
    secrets:
      name: myminio-env-configuration
      accessKey: minio 
      secretKey: minio123
    tenant:
      name: myminio
      configuration:
        name: myminio-env-configuration
      pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        size: 25Gi
      features:
        bucketDNS: false
        domains: { }
        enableSFTP: false