---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: minio-operator
spec:
  ingressClassName: nginx
  rules:
    - host: minio.goobyplz.duckdns.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: console
                port:
                  number: 9090