name: Renovate
on:
  workflow_dispatch:
    inputs:
        logLevel:
            description: Log Level
            default: info
            required: false
  schedule:
    - cron: '0/10 * * * *'

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/renovate/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}